version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DATABASE: properties_listings
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: postgres
      - POSTGRES_HOST: db
      - POSTGRES_PORT: 5432
    depends_on:
      - db
      - cache

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DATABASE: properties_listings
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: postgres
      - POSTGRES_PORT: 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
